import {DIRECTION_BUY, DIRECTION_SELL, STATUS_CANCELED, STATUS_CLOSED, STATUS_OPEN} from "./Order"

let ORDERS_DIRECTION_COLORS = {}
ORDERS_DIRECTION_COLORS[DIRECTION_SELL] = 'red'
ORDERS_DIRECTION_COLORS[DIRECTION_BUY] = '#6BA583'

let ORDERS_STATUS_COLORS = {}
ORDERS_STATUS_COLORS[STATUS_OPEN] = 'orange'
ORDERS_STATUS_COLORS[STATUS_CLOSED] = 'blue'
ORDERS_STATUS_COLORS[STATUS_CANCELED] = 'black'

export {
 ORDERS_DIRECTION_COLORS,
 ORDERS_STATUS_COLORS,
}
